<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>Audit Logs Report</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 20px;
            color: #333;
        }

        h1 {
            color: #1f2937;
            border-bottom: 2px solid #3b82f6;
            padding-bottom: 10px;
        }

        .header {
            margin-bottom: 30px;
        }

        .meta {
            font-size: 12px;
            color: #666;
            margin-bottom: 20px;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 30px;
        }

        th {
            background-color: #f3f4f6;
            padding: 10px;
            text-align: left;
            font-weight: bold;
            font-size: 12px;
            border-bottom: 2px solid #e5e7eb;
        }

        td {
            padding: 10px;
            border-bottom: 1px solid #e5e7eb;
            font-size: 11px;
        }

        tr:nth-child(even) {
            background-color: #f9fafb;
        }

        .event-created {
            color: #dc2626;
        }

        .event-updated {
            color: #1f2937;
        }

        .event-deleted {
            color: #ea580c;
        }

        .event-critical {
            color: #dc2626;
            font-weight: bold;
        }

        .page-break {
            page-break-after: always;
        }

        .footer {
            text-align: center;
            font-size: 10px;
            color: #999;
            margin-top: 40px;
            border-top: 1px solid #e5e7eb;
            padding-top: 10px;
        }
    </style>
</head>

<body>
    <div class="header">
        <h1>Audit Logs Report</h1>
        <div class="meta">
            <p><strong>Generated:</strong> {{ now()->format('M d, Y H:i:s') }}</p>
            <p><strong>Total Records:</strong> {{ count($auditLogs) }}</p>
        </div>
    </div>

    <table>
        <thead>
            <tr>
                <th style="width: 12%;">Date/Time</th>
                <th style="width: 12%;">User</th>
                <th style="width: 10%;">Event</th>
                <th style="width: 15%;">Model</th>
                <th style="width: 12%;">IP Address</th>
                <th style="width: 15%;">URL</th>
                <th style="width: 10%;">Method</th>
            </tr>
        </thead>
        <tbody>
            @forelse($auditLogs as $log)
                <tr>
                    <td>{{ $log->created_at->format('M d, Y H:i') }}</td>
                    <td>{{ $log->user?->email ?? 'System' }}</td>
                    <td class="
                            @if(in_array($log->event, ['role_changed', 'force_deleted', '2fa_disabled']))
                                event-critical
                            @elseif($log->event === 'created')
                                event-created
                            @elseif($log->event === 'deleted')
                                event-deleted
                            @else
                                event-updated
                            @endif
                        ">
                        {{ ucfirst(str_replace('_', ' ', $log->event)) }}
                    </td>
                    <td>
                        @if($log->auditable_type)
                            {{ class_basename($log->auditable_type) }} #{{ $log->auditable_id }}
                        @else
                            -
                        @endif
                    </td>
                    <td>{{ $log->metadata['ip_address'] ?? 'N/A' }}</td>
                    <td style="word-break: break-all;">{{ $log->metadata['url'] ?? 'N/A' }}</td>
                    <td>{{ $log->metadata['method'] ?? 'N/A' }}</td>
                </tr>
            @empty
                <tr>
                    <td colspan="7" style="text-align: center; color: #999;">
                        No audit logs found
                    </td>
                </tr>
            @endforelse
        </tbody>
    </table>

    <div class="footer">
        <p>This report contains sensitive audit trail information. Handle with appropriate confidentiality.</p>
        <p>Page generated by PageTurner Bookstore System</p>
    </div>
</body>

</html>